#!/bin/bash

b "cleaning up after build..."
apt-get -qq clean
rm -rf \
  /var/lib/apt/lists/* \
  /tmp/* \
  /var/tmp/* \
  /var/log/apt \
  /var/log/dpkg.log \
  /var/log/alternatives.log \
  /var/log/bootstrap.log \
  /var/log/faillog \
  /var/log/lastlog \
  /var/log/dmesg \
  /var/log/fsck \
  /var/log/btmp \
  /var/log/wtmp \
  /var/log/upstart \
  /var/log/unattended-upgrades
bl OK
