#!/bin/bash

### FUNCTIONS
function join_json_fields {
  local IFS=','
  echo -n "$*"
}

function help () {
  echo "Usage: $(basename $0) [OPTIONS] SVC"
  echo "  -i  list only service IPs"
  echo "  -y  output in YAML"
  echo "  -h  output in JSON"
  echo "  -h  help"
}

function svc_list () {
  grep $1 /etc/hosts | grep -Pv '\.[a-z0-9]+$' | sort
}

function print_text () {
  if $2
  then
    svc_list $1 | awk '{ print $1 }'
  else
    svc_list $1 | awk '{ print $2" "$1 }'
  fi
}

function print_yaml () {
  echo '---'
  if `grep -q $1 /etc/hosts`
  then
    svc_list $1 | awk '{ print $2": "$1 }'
  else
    echo '{}'
  fi
}

function print_json () {
  echo -n '{'
  join_json_fields $(svc_list $1 | awk '{ print "  \""$2"\":\""$1"\"" }')
  echo '}'
}

### OPTIONS
IP=false
YAML=false
JSON=false

while getopts ":iyjh" opt
do
  case ${opt} in
    i) IP=true ;;
    y) YAML=true ;;
    j) JSON=true ;;
    h) help && exit 0 ;;
    *) help && echo "\nUnknown parameter!" && exit 1 ;;
  esac
done

### INIT
shift $(($OPTIND-1))
SVC=$1

if [ -z ${SVC} ]
then
  echo -e 'You have to specify service name!\n' 1>&2
  help
  exit 1
fi

### MAIN
if   $YAML; then print_yaml $SVC;
elif $JSON; then print_json $SVC;
else             print_text $SVC $IP;
fi
